from django.conf.urls import path, re_path
from django.views.generic.base import TemplateView

from votefinder.main import feeds, views

urlpatterns = [
    path('/', views.index),
    path('add/', views.add),
    path('add_game/', views.add_game),
    re_path(r'^game_list/(?P<page>\d+)/*$', views.game_list),
    re_path(r'^game/(?P<slug>[\w-]+)$', views.game),
    re_path(r'^player/(?P<slug>[\w-]+)/*$', views.player),
    re_path(r'^claim_player/(?P<playerid>\d+)/*$', views.claim_player),
    re_path(r'^p:(?P<playerid>\d+)/*$', views.player_id),
    re_path(r'^profile/*$', views.profile),
    re_path(r'^update/(?P<gameid>\d+)/*$', views.update),
    re_path(r'^player_state/(?P<gameid>\d+)/(?P<playerid>\d+)/(?P<state>\w+)/$', views.player_state),
    path('player_list/', views.player_list),
    path('add_player/<int:gameid>/', views.add_player),
    path('delete_spectators/<int:gameid>/', views.delete_spectators),
    path('votecount/<int:gameid>/', views.votecount),
    re_path(r'^resolve/(?P<voteid>\d+)/(?P<resolution>-{0,1}\d+)/*$', views.resolve),
    re_path(r'^posts/(?P<gameid>\d+)/(?P<page>\d+)/*$', views.posts),
    path('add_comment/<int:gameid>/', views.add_comment),
    path('delete_comment/<int:commentid>/', views.delete_comment),
    path('rss/', feeds.LatestRss()),
    path('atom/', feeds.LatestAtom()),
    re_path(r'^game_status/(?P<slug>[\w-]+)/*', feeds.SpecificGameStatusAtom()),
    path('game_status/', feeds.GameStatusAtom()),
    path('faq/', TemplateView.as_view(template_name='faq.html')),
    re_path(
        r'^deadline/(?P<gameid>[\d]+)/(?P<month>[\d]+)/(?P<day>[\d]+)/(?P<year>[\d]+)/(?P<hour>[\d]+)/(?P<minute>[\d]+)/(?P<ampm>[\w]+)/(?P<tzname>.+)$',
        views.deadline),
    re_path(r'^close_game/(?P<gameid>\d+)/*$', views.close_game),
    re_path(r'^start_game/(?P<gameid>\d+)/(?P<day>\d+)/*$', views.start_game),
    re_path(r'^reopen_game/(?P<gameid>\d+)/*$', views.reopen_game),
    re_path(r'^new_day/(?P<gameid>\d+)/(?P<day>\d+)/*$', views.new_day),
    re_path(r'^replace/(?P<gameid>\d+)/(?P<clear>\w+)/(?P<outgoing>\d+)/(?P<incoming>.+)*$', views.replace),
    re_path(r'^startday/(?P<day>\d+)/(?P<postid>\d+)*$', views.start_day),
    path('templates/', views.templates),
    path('create_template/', views.create_template),
    re_path(r'^template/(?P<templateid>\d+)$', views.edit_template),
    re_path(r'^delete_template/(?P<templateid>\d+)$', views.delete_template),
    re_path(r'^game_template/(?P<gameid>\d+)/(?P<templateid>\d+)', views.game_template),
    path('active_games/', views.active_games),
    path('active_games/json/', views.active_games_json),
    re_path(r'^active_games/(?P<style>.+)', views.active_games_style),
    path('closed/', views.closed_games),
    re_path(r'^add_vote/(?P<gameid>\d+)/(?P<player>[\d-]+)/(?P<votes>\w+)/(?P<target>\d+)$',
            views.add_vote),
    re_path(r'^add_vote_global/(?P<gameid>\d+)$', views.add_vote_global),
    re_path(r'^delete_vote/(?P<voteid>\d+)$', views.delete_vote),
    re_path(r'^add_faction/(?P<gameid>\d+)$', views.add_faction),
    re_path(r'^delete_faction/(?P<factionid>\d+)$', views.delete_faction),
    re_path(r'^img/(?P<slug>[\w-]+)/*$', views.votecount_image),
    path('autoupdate/', views.autoupdate),
    path('players/', views.players),
    re_path(r'^players/(?P<page>\d+)$', views.players_page),
    re_path(r'^delete_alias/(?P<aliasid>\d+)$', views.delete_alias),
    re_path(r'^sendpms/(?P<slug>[\w-]+)$', views.sendpms),
    re_path(r'^post_histories/(?P<gameid>\d+)$', views.post_histories),
    re_path(r'^post_executions/(?P<gameid>\d+)/(?P<enabled>\w+)$', views.post_executions),
    re_path(r'^ecco_mode/(?P<gameid>\d+)/(?P<enabled>\w+)$', views.ecco_mode),
    re_path(r'^post_vc/(?P<gameid>\d+)$', views.post_vc),
    re_path(r'^votechart/(?P<gameslug>[\w-]+)$', views.votechart_all),
    re_path(r'^votechart/(?P<gameslug>[\w-]+)/(?P<playerslug>[\w-]+)$', views.votechart_player),
    path('gamechart/', views.gamechart),
    path('update_user_theme/', views.update_user_theme),
    path('update_user_pronouns/', views.update_user_pronouns),
    re_path(r'^players/common_games/(?P<slug_a>[\w-]+)/(?P<slug_b>[\w-]+)', views.common_games),
]
