# Generated by Django 2.2.13 on 2020-06-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstate',
            name='faction',
            field=models.ManyToManyField(to='main.GameFaction'),
        ),
        migrations.DeleteModel(
            name='PlayerFaction',
        ),
    ]
