# Generated by Django 2.2.13 on 2020-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200625_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='home_forum',
            field=models.TextField(default='sa'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thread_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
