# Generated by Django 2.2.13 on 2020-07-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200625_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
