# Generated by Django 3.0.8 on 2020-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200717_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
