# Generated by Django 3.0.8 on 2020-12-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200930_1751'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('post_id', 'game'), name='unique_postid_game'),
        ),
    ]
